/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author wolfram77
 */
public class PinsetterPanel extends javax.swing.JPanel {

  /**
   * Creates new form PinsetterPanel
   */
  public PinsetterPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel5 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    pinsTable = new javax.swing.JTable();
    pinsetterLabel = new javax.swing.JLabel();
    dataPanel = new javax.swing.JPanel();
    turnLabel = new javax.swing.JLabel();
    turnValue = new javax.swing.JLabel();
    standingLabel = new javax.swing.JLabel();
    standingValue = new javax.swing.JLabel();

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel5.setText("_");

    pinsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"7", "", "8", "", "9", null, "10"},
        {null, "", null, "", null, "", null},
        {null, "4", null, "5", null, "6", null},
        {null, null, null, null, null, null, null},
        {null, null, "2", null, "3", null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, "1", null, null, null}
      },
      new String [] {
        "C0", "C1", "C2", "C3", "C4", "C5", "C6"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane1.setViewportView(pinsTable);

    pinsetterLabel.setBackground(new java.awt.Color(204, 204, 204));
    pinsetterLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    pinsetterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    pinsetterLabel.setText("Pinsetter");
    pinsetterLabel.setBorder(new javax.swing.border.MatteBorder(null));

    turnLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    turnLabel.setText("Turn");

    turnValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    turnValue.setText("0");

    standingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    standingLabel.setText("Standing");

    standingValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    standingValue.setText("0");

    javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
    dataPanel.setLayout(dataPanelLayout);
    dataPanelLayout.setHorizontalGroup(
      dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanelLayout.createSequentialGroup()
        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(turnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(standingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(standingValue, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
          .addComponent(turnValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    dataPanelLayout.setVerticalGroup(
      dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dataPanelLayout.createSequentialGroup()
        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(turnLabel)
          .addComponent(turnValue, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(standingLabel)
          .addComponent(standingValue, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    standingValue.getAccessibleContext().setAccessibleDescription("");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
        .addComponent(dataPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, Short.MAX_VALUE)
        .addComponent(pinsetterLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(pinsetterLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    dataPanel.getAccessibleContext().setAccessibleName("Data");
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel dataPanel;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable pinsTable;
  private javax.swing.JLabel pinsetterLabel;
  private javax.swing.JLabel standingLabel;
  private javax.swing.JLabel standingValue;
  private javax.swing.JLabel turnLabel;
  private javax.swing.JLabel turnValue;
  // End of variables declaration//GEN-END:variables
}
